/*
 *  fractal2D_renderer.h -- part of fractal2D
 *
 *  Copyright (c) 2011 Marc Pegon <pe.marc@free.fr>
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */
 
 /**
  * \file fractal.h
  * \brief Main header file for fractal2D_renderer program.
  * \author Marc Pegon
  */
 
#ifndef __FRACTAL2D_RENDERER_H__
#define __FRACTAL2D_RENDERER_H__

#include "floating_point.h"
#include <stdint.h>

/**
 * \enum e_AntiAliasingMethod
 * \brief Possible anti-aliasing methods.
 */
typedef enum e_AntiAliasingMethod {
	AAM_NONE = 0, /*!< No anti-aliasing.*/
	AAM_GAUSSIANBLUR, /*!< Gaussian Blur.*/
	AAM_OVERSAMPLING /*!< Over sampling (compute a bigger image and scale it down).*/
} AntiAliasingMethod;

/**
 * \struct s_CommandLineArguments
 * \brief For storing command lines arguments.
 *
 * This structure is to store the arguments given on the command line.
 */
typedef struct s_CommandLineArguments {
	char *floatTableFileName;
 /*!< Input table of floats file name (generated by fractal2D-computer).*/
	char *renderingFileName;
 /*!< Rendering file name.*/
	char *dstFileName;
 /*!< Output image file name.*/
	AntiAliasingMethod antiAliasingMethod;
 /*!< Anti-aliasing method.*/
	FLOAT downscalingFactor;
 /*!< Downscaling factor (used when anti-aliasing method is oversampling).*/
	FLOAT gaussianBlurRadius;
 /*!< Gaussian blur radius (used when anti-aliasing method is gaussian blur).*/
} CommandLineArguments;

/**
 * \fn void DisplayHelp()
 * \brief Display program help.
 */
void DisplayHelp();

/**
 * \fn void ParseCommandLineArguments(CommandLineArguments *dst, int argc, char *argv[])
 * \brief Parse arguments given on command line.
 *
 * \param dst Pointer to the (already allocated) structure in which to store the arguments.
 * \param argc Argc of the main function
 * \param argv Argv of the main function
 */
void ParseCommandLineArguments(CommandLineArguments *dst, int argc, char *argv[]);

#endif
